// Constantes de rutas para GoRouter
// NUNCA usar Navigator.push() — siempre context.push(AppRoutes.xxx)
class AppRoutes {
  static const String home               = '/';
  static const String appointments       = '/appointments';
  static const String appointmentDetail  = '/appointments/:id';
  static const String scheduleType       = '/appointments/schedule-type';
  static const String schedule           = '/appointments/schedule';
  static const String scheduleTests      = '/appointments/schedule-tests';
  static const String consultSymptoms    = '/appointments/consult';
  static const String consultBranch      = '/appointments/consult/branch';
  static const String consultDateTime    = '/appointments/consult/datetime';
  static const String consultPatientInfo = '/appointments/consult/patient-info';
  static const String consultConfirmation = '/appointments/consult/confirmation';
  static const String consultSuccess     = '/appointments/consult/success';
  static const String vaccineType        = '/appointments/vaccine';
  static const String vaccineQuestionnaire = '/appointments/vaccine/questionnaire';
  static const String vaccineBranch        = '/appointments/vaccine/branch';
  static const String vaccineDateTime      = '/appointments/vaccine/datetime';
  static const String vaccinePatientInfo   = '/appointments/vaccine/patient-info';
  static const String vaccineConfirmation  = '/appointments/vaccine/confirmation';
  static const String vaccineSuccess       = '/appointments/vaccine/success';
  static const String vaccinePayInBranch   = '/appointments/vaccine/pay-in-branch';
  static const String testType         = '/appointments/test';
  static const String testBranch       = '/appointments/test/branch';
  static const String testDateTime     = '/appointments/test/datetime';
  static const String testPatientInfo  = '/appointments/test/patient-info';
  static const String testConfirmation = '/appointments/test/confirmation';
  static const String testSuccess      = '/appointments/test/success';
  static const String testValidating   = '/appointments/test/validating';
  static const String prescriptionScan          = '/prescription-scan';
  static const String prescriptionDeliveryNote  = '/prescription-delivery-note';
  static const String healthRecord       = '/health-record';
  static const String prescriptions      = '/health-record/prescriptions';
  static const String documentsList      = '/health-record/documents-list';
  static const String prescriptionDetail = '/health-record/prescription/:id';
  static const String documentDetail     = '/health-record/document/:id';
  static const String signDocument       = '/sign-document/:id';
  static const String videoCall          = '/video-call';
  static const String account            = '/account';
}
